START TRANSACTION;
USE `atelie_v1`;

INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (1, 1, 'Pintura', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (2, 1, 'Corte', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (3, 2, 'Costa', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (4, 2, 'Pé', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (5, 3, 'Teste', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (6, 4, 'dsdsad', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (7, 1, 'Corte', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (8, 1, 'Valor', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (9, 5, 'Massagem', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (10, 6, 'Mão', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (11, 6, 'Pé', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (12, 6, 'Pé e Mão', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (13, 7, 'Manicure e Pedicure infantil', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (14, 7, 'Colocação de unhas de acrigel', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (15, 7, 'Manicure e Pedicure Importado', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (16, 7, 'Pés Infantil', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (17, 7, 'Unhas de Porcelana Manutenção', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (18, 7, 'Unhas Postiças Material do Profissional ( colocação )', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (19, 7, 'Unhas Postiças Material do Cliente (colocação)', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (20, 7, 'Mãos infantil', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (21, 7, 'Unhas de  Acrigel Manutenção', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (22, 7, 'Banho de gel ', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (23, 7, 'Unhas de  Fibra Manutenção', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (24, 7, 'Banho de fibra de vidro', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (25, 7, 'Unhas de Gel Manutenção', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (26, 7, 'Manicure e Pedicure ', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (27, 7, 'Manicure', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (28, 7, 'Colocação de unhas de gel', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (29, 7, 'Esmaltação Mão', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (30, 7, 'Esmaltação Pés', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (31, 7, 'Esmaltação Importada Mão', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (32, 7, 'Esmaltação Importada Pés', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (33, 7, 'Manicure Esmalte Importado', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (34, 7, 'Corte, lixação e retirada de cutículas pés e mãos masc.', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (35, 7, 'Pés e Mãos', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (36, 7, 'Colocação de unhas de porcelana ', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (37, 7, 'Colocação de unhas de fibra de vidro ', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (38, 7, 'Corte e lixação de pés e mãos masc.', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (39, 7, 'Manicure e Pedicure Esmalte de Gel', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (40, 7, 'Pés ', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (41, 7, 'Mãos ', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (42, 7, 'Remoção Alongamentos em gel', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (43, 8, 'Argiloterapia', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (44, 8, 'Peeling Químico Superficial', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (45, 8, 'Rejuvenescimento Facial', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (46, 8, 'Controle de Oleosidade', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (47, 8, 'Hidratação Cutânea', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (48, 8, 'Limpeza de Pele ', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (49, 8, 'Drenagem Facial', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (50, 9, 'Designer de Sobrancelha na Pinça ', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (51, 9, 'Sobrancelha Henna', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (52, 9, 'Micropigmentação ', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (53, 9, 'Cílio Fio a Fio 3D', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (54, 10, 'Tratamento tradicional ( corte técnico das unhas,remoção de calos,calosidades)', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (55, 10, 'Procedimento Normal + Infeccão de uma (1) unha (granulomas/micose/onicomicose)', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (56, 10, 'Tratamento de Infecção de uma (1) unha (granulomas/micose/onicomicose)', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (57, 11, 'Hidratação', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (58, 11, 'Penteado Simples', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (59, 11, 'Penteado Festa', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (60, 11, 'Corte', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (61, 11, 'Chapinha', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (62, 11, 'Cachos', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (63, 11, 'Cauterização', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (64, 11, 'Escova Cabelo Curto', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (65, 11, 'Escova Cabelo Médio', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (66, 11, 'Escova Cabelo Longo', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (67, 12, ' Massagem Modeladora', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (68, 12, '  Massagem Relaxante', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (69, 12, 'Drenagem  Linfática', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (70, 13, 'Social Dia', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (71, 13, 'Social Noite', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (72, 13, 'Festa', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (73, 13, 'Noiva', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (74, 14, ' Barriga', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (75, 14, ' Axilas', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (76, 14, ' Braços', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (77, 14, ' Buço', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (78, 14, ' Meia Perna', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (79, 14, ' Meio Braço', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (80, 14, ' Orelha', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (81, 14, ' Perna Inteira', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (82, 14, 'Depilação de Queixo', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (83, 14, 'Virilha Completa', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (84, 14, ' Virilha Cavada', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (85, 16, 'Batom', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (86, 14, 'Depilação facial', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (87, 14, 'Depilação facial', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (88, 14, 'Depilação completa', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (89, 8, 'Hidratação cutânea ', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (90, 13, 'Maquiagem artística ', 0);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (91, 10, 'Tratamento de infecção de duas (2) unhas', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (92, 10, 'Reflexologia podal ( sessão de massagem relaxante nos pés)', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (93, 10, 'Cauterização de verruga plantar', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (94, 10, 'Tratamento de calo infeccionado ', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (95, 10, 'Tratamento tradicional + Hidratação com parafina', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (96, 10, 'Tratamento tradicional + Reflexologia', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (97, 10, 'Remoção de calosidades', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (98, 10, 'Tratamento tradicional + Desinfecção de uma (1) unha ', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (99, 10, 'Tratamento tradicional + Desinfecção de duas (2) unhas', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (100, 10, 'Corte técnico das unhas', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (101, 10, 'Curativo', 1);
INSERT INTO `atelie_v1`.`sub_categoria` (id, categoria, nome, ativo) VALUES (102, 9, 'Micropigmentação', 0);

COMMIT;